# Training
batch_size: 2

# Dataset parameters
dataset_file: 'coco'
#mindrecord_dir: C:\02Data\coco2017\MindRecord_COCO_detr
#coco_path: C:\02Data\coco2017
mindrecord_dir: /data1/coco2017/MindRecord_COCO_detr
coco_path: /data1/coco2017/coco_ori/
train_data_type: "train2017"
val_data_type: 'val2017'
output_dir: './work_dirs'
num_parallel_workers: 8
python_multiprocessing: False

# Augment
max_size: 960
flip_ratio: 0.5

distributed: False
